Module7 task1
htmlacademy-ecmascript/367171-cinemaddict-12 pull request #11
Opened 2020-09-27 14:50 UTC by cybersunt

2020-09-29 04:32 UTC, Shv-sergey70 requested changes

2020-09-29 04:32 UTC, Shv-sergey70 commented on src/view/movie-card-details.js
> +          <p class="film-details__comment-text">${he.encode(comment.message)}</p>
Ошибка возникает, потому что ты передаешь в `he.encode` не строку, а массив. Поменяй логику в моках так, что в `message` была именно строка, тогда все должно будет заработать

2020-09-29 04:32 UTC, Shv-sergey70 commented on src/view/movie-card-details.js
> +    this.getElement().querySelector(`.film-details__comment-delete`).addEventListener(`click`, this._commentDeleteClickHandler);
Обработчик добавится только на первую кнопку `delete`

2020-09-29 04:32 UTC, Shv-sergey70 commented on src/view/movie-card-details.js
> +  _commentDeleteClickHandler(evt) {
Метод нужно забиндить, this теряется

2020-09-29 18:58 UTC, cybersunt commented on src/view/movie-card-details.js
> +    }
после вынесения этого кода в отдельную функцию, появилась ошибка в консоли:
```
Uncaught TypeError: Cannot read property 'replace' of null
    at Object.encode (he.js:202)
    at movie-card-details.js:75
```

2020-09-30 02:21 UTC, Shv-sergey70 commented on src/view/movie-card-details.js
> +    }
Не могу воспроизвести, опиши что ты делала, чтобы возникла ошибка. Текущий код актуальный?

Поправь конфликт, для этого надо смержить мастер в текущую ветку:
![Снимок экрана 2020-09-30 в 9 18 10](https://user-images.githubusercontent.com/35741647/94635994-20319080-02fe-11eb-92bb-df5f581cd665.png)

2020-09-30 11:16 UTC, cybersunt commented on src/view/movie-card-details.js
> +    }
Отправляла комментарий

2020-09-30 16:05 UTC, merged