Module5 task1
htmlacademy-ecmascript/367171-cinemaddict-12 pull request #7
Opened 2020-09-08 20:16 UTC by cybersunt

Ошибка в браузере
Uncaught TypeError: movieListContainer.querySelector is not a function
    at new Movie (movie.js:8)
    at MoviesList._renderMovie (movies-list.js:24)
    at movies-list.js:31
    at Array.forEach (<anonymous>)
    at MoviesList._renderMovies (movies-list.js:31)
    at MoviesList._renderMainMovieList (movies-list.js:43)
    at MoviesList._renderMoviesList (movies-list.js:56)
    at MoviesList.init (movies-list.js:20)
    at Board._renderMoviesList (board.js:35)
    at Board._renderBoard (board.js:44)

2020-09-09 04:00 UTC, Shv-sergey70 requested changes
А зачем тебе сразу 3 контроллера?
По заданию пока нужен только 1 - список фильмов

2020-09-09 04:00 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +    const moviePresenter = new Movie(this._moviesContainer);
Сейчас ты передаешь компонент, а не контейнер как дом-элемент:
`new Movie(this._moviesContainer.getElement());`

2020-09-09 04:00 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +  _renderMovie(movie) {
Метод принимает 1 параметр, а на 31 строке ты передаешь 2 параметра. Что-то тут не так

2020-09-09 07:10 UTC, cybersunt commented
> А зачем тебе сразу 3 контроллера?
> По заданию пока нужен только 1 - список фильмов

На борде тренировалась, а в movie-list как-то не хочется все колбасу кода собирать.. Мы movie же потом отдельно вынесем.
Для того, что мы рендерим в `main` контроллер вообще нужен?

2020-09-11 09:19 UTC, Shv-sergey70 commented on src/main.js
> +mainInner.init(movies);
Если экземпляр класса используется только для вызова одного метода, то можно не сохранять его в переменную:
`new Board(siteMainElement, filters).init(movies);`

2020-09-11 09:19 UTC, Shv-sergey70 commented on src/main.js
> +render(siteFooterElement, new MovieStatsView(movies), RenderPosition.BEFOREEND);
`MovieStatsView ` - этому компоненту незачем на вход принимать все фильмы. Стоит сразу передать только их количество

2020-09-11 09:20 UTC, merged