Module6 task1
htmlacademy-ecmascript/367171-cinemaddict-12 pull request #9
Opened 2020-09-24 08:51 UTC by cybersunt

**Настроим частичный датабиндинг**

1. После добавления метода `destroy` очищение списков стало себя странно вести. После сортировки фильмы из списка **Most commented** переползают в основной список
2. Обновленные данные не передаются после нажатия на кнопки и чекбоксы и фильм из списка исчезает

2020-09-24 13:49 UTC, Shv-sergey70 requested changes
__При выборе смайлика всегда активный почему-то последний__
Потому что у всех label одинаковый атрибут `for`

__Непонятно какое условие нужно, чтобы отобразить выбранный смайл рядом с полем textarea__
Есть версии как это можно сделать?

__Есть проблемы с отправкой формы по событию Enter__
Какие проблемы?

2020-09-24 13:49 UTC, Shv-sergey70 commented on src/presenter/movie.js
> +    remove(prevMovieCardComponent);
__Обновленные данные не передаются после нажатия на кнопки и чекбоксы и фильм из списка исчезает__
А где код по замене movieCardComponent после изменения данных?
Я вижу тут только удаление, поэтому они и исчезают

2020-09-24 13:49 UTC, Shv-sergey70 commented on src/presenter/movie.js
> +    remove(prevMovieCardComponent);
Например в учебном проект вот есть замена:
https://github.com/htmlacademy-ecmascript/taskmanager-12/pull/9/files#diff-dfd4073651f56c30f693c0ef3eb6d52bR47

2020-09-24 13:49 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +    this._moviePresenter[movie.id] = moviePresenter;
__После добавления метода destroy очищение списков стало себя странно вести. После сортировки фильмы из списка Most commented переползают в основной список__

Обрати внимание, что ты отрисовываешь презентеры и сохраняешь их в переменную `this. _moviePresenter`. Любые презентеры - вне зависимости от того из основного они списка или из дополнительных.

Так как ты сохраняешь презентеры по ключу фильма - то для одного фильма может создаться 2 презентера (один в основном списке и один в дополнительном). Но так как ключ будет одинаковый - презентер из дополнительного списка перезапишет презентер из основного.

Поэтому тебе кажется что обработчики себя странно ведут.

Как вариант - сохраняй презентеры основного и каждого доп списка в отдельные свойства класса.

Когда ты вызываешь метод `_clearMainMovieList` - удаляются те презентеры, на которые есть ссылка в `this._moviePresenter`. Но так как некоторые затираются - они не могут удалиться из основного списка

2020-09-24 13:49 UTC, Shv-sergey70 commented on src/main.js
> +export const mainInner = new Board(siteMainElement, filters);
Зачем это экспортируется?

2020-09-24 14:55 UTC, cybersunt commented on src/main.js
> +export const mainInner = new Board(siteMainElement, filters);
не удалила

2020-09-24 15:03 UTC, cybersunt commented on src/presenter/movie.js
> +    remove(prevMovieCardComponent);
В учебном проекте заменяются карточки компонентов при клике на кнопку. Здесь же происходит удаление старых компонентов до обновления

2020-09-24 16:08 UTC, cybersunt commented
> Есть версии как это можно сделать?

проверить у чекнутого инпута какой смайл и эту разметку вставить в код лейбла.

2020-09-26 04:10 UTC, Shv-sergey70 requested changes

2020-09-26 04:10 UTC, Shv-sergey70 commented on src/presenter/movie.js
> +    if (this._mode === Mode.DEFAULT) {
Это условие не нужно, иначе при открытом попапе карточки обновляться не будут, но будут удалены. Нужно делать `replace` без условий

2020-09-26 04:10 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +    }
Этот код однотипно дублируется три раза - попробуй для него создать приватный метод

2020-09-26 04:10 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +      .forEach((presenter) => presenter.resetView());
Можно собрать разом все презентеры так:
```
[
      ...Object.values(this._movieMainPresenter),
      ...Object.values(this._movieTopRatedPresenter),
      ...Object.values(this._movieMostCommentedPresenter)
    ].forEach() // логика
```

2020-09-26 04:10 UTC, Shv-sergey70 commented on src/presenter/movies-list.js
> +  _handleModeChange() {
Чтобы метод не выкидывал ошибок - нужно его забиндить. Сейчас меняется контекст при вызове

2020-09-26 12:51 UTC, Shv-sergey70 approved these changes
В целом все ок, но есть один баг:
Если ты откроешь любой попап - нажмешь на любую кнопку (н-р favorites) - то попап перерисуется, но после этого уже нажатие на кнопки не приводит к изменению данных и перерисовке попапа. Крестик также перестает работать.

Это связано с тем, что обработчики ты добавляешь только один раз, при выполнении метода `_handleMovieCardClick`. Но ведь при перерисовке попапа этот метод уже не срабатывает и обработчиков - нет. Подумай как это можно поправить.

2020-09-26 12:51 UTC, merged